[package]
name = "db_interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "db_interface"
path = "src/db_interface.rs"

[dependencies]
sqlite = "0.30.2"